/**
 * Roles and permissions (USR-01), as approved by the founder in
 * docs/MATRIZ_ROLES_PERMISOS.md (FUN-07). catalog.test.ts compares this file
 * with the document: change both together.
 *
 * The titular is not a role: it is Organization.ownerUserId and gets
 * OWNER_PERMISSIONS. Roles combine (permissions are joined) and never
 * grant anything outside their list (deny by default).
 */

export const ROLES = ["administrator", "warehouse", "buyer", "viewer"] as const;
export type Role = (typeof ROLES)[number];

/** Names shown in the interface. */
export const ROLE_LABELS: Record<Role, string> = {
  administrator: "Administrador",
  warehouse: "Almacén",
  buyer: "Comprador",
  viewer: "Consulta",
};

export const PERMISSIONS = [
  "platform.organization.read",
  "platform.organization.update",
  "platform.team.read",
  "platform.team.invite",
  "platform.invitation.resend",
  "platform.invitation.cancel",
  "platform.team.assign_roles",
  "platform.team.disable",
  "platform.ownership.transfer",
  "platform.audit.read",
  "platform.module.read",
  "platform.capacity.read",
  "platform.plan.read",
  "platform.plan.change",
  "platform.module.activate",
  "platform.module.deactivate",
  "platform.subscription.create",
  "platform.subscription.cancel",
  "platform.billing.read",
  "platform.billing.manage",
  "platform.provisioning.manage",
  "inventory.product.read",
  "inventory.product.create",
  "inventory.product.update",
  "inventory.product.archive",
  "inventory.product.reactivate",
  "inventory.unit.read",
  "inventory.presentation.read",
  "inventory.presentation.create",
  "inventory.presentation.update",
  "inventory.location.read",
  "inventory.location.create",
  "inventory.location.update",
  "inventory.location.archive",
  "inventory.stock.read",
  "inventory.movement.read",
  "inventory.minimum.read",
  "inventory.minimum.update",
  "inventory.dashboard.read",
  "inventory.entry.create",
  "inventory.opening.create",
  "inventory.exit.create",
  "inventory.transfer.create",
  "inventory.adjustment.create",
  "inventory.movement.reverse",
  "inventory.count.read",
  "inventory.count.create",
  "inventory.count.update",
  "inventory.count.apply",
  "inventory.import.create",
  "inventory.import.read",
  "inventory.import.confirm",
  "inventory.import.cancel",
  "inventory.export.create",
  "purchasing.supplier.read",
  "purchasing.supplier.create",
  "purchasing.supplier.update",
  "purchasing.product_supplier.read",
  "purchasing.product_supplier.create",
  "purchasing.product_supplier.update",
  "purchasing.cost.read",
  "purchasing.cost.record",
  "purchasing.order.read",
  "purchasing.order.create",
  "purchasing.order.update",
  "purchasing.order.submit",
  "purchasing.order.export",
  "purchasing.order.send",
  "purchasing.order.cancel",
  "purchasing.order.close",
  "purchasing.receipt.read",
  "purchasing.receipt.create",
  "purchasing.return.read",
  "purchasing.return.create",
  "purchasing.suggestion.read",
  "purchasing.suggestion.generate",
  "purchasing.report.read",
  "purchasing.report.export",
] as const;
export type Permission = (typeof PERMISSIONS)[number];

/** Everything the titular can do in their company. */
export const OWNER_PERMISSIONS: readonly Permission[] = [
  "platform.organization.read",
  "platform.organization.update",
  "platform.team.read",
  "platform.team.invite",
  "platform.invitation.resend",
  "platform.invitation.cancel",
  "platform.team.assign_roles",
  "platform.team.disable",
  "platform.ownership.transfer",
  "platform.audit.read",
  "platform.module.read",
  "platform.capacity.read",
  "platform.plan.read",
  "platform.plan.change",
  "platform.module.activate",
  "platform.module.deactivate",
  "platform.subscription.create",
  "platform.subscription.cancel",
  "platform.billing.read",
  "platform.billing.manage",
  "inventory.product.read",
  "inventory.product.create",
  "inventory.product.update",
  "inventory.product.archive",
  "inventory.product.reactivate",
  "inventory.unit.read",
  "inventory.presentation.read",
  "inventory.presentation.create",
  "inventory.presentation.update",
  "inventory.location.read",
  "inventory.location.create",
  "inventory.location.update",
  "inventory.location.archive",
  "inventory.stock.read",
  "inventory.movement.read",
  "inventory.minimum.read",
  "inventory.minimum.update",
  "inventory.dashboard.read",
  "inventory.entry.create",
  "inventory.opening.create",
  "inventory.exit.create",
  "inventory.transfer.create",
  "inventory.adjustment.create",
  "inventory.movement.reverse",
  "inventory.count.read",
  "inventory.count.create",
  "inventory.count.update",
  "inventory.count.apply",
  "inventory.import.create",
  "inventory.import.read",
  "inventory.import.confirm",
  "inventory.import.cancel",
  "inventory.export.create",
  "purchasing.supplier.read",
  "purchasing.supplier.create",
  "purchasing.supplier.update",
  "purchasing.product_supplier.read",
  "purchasing.product_supplier.create",
  "purchasing.product_supplier.update",
  "purchasing.cost.read",
  "purchasing.cost.record",
  "purchasing.order.read",
  "purchasing.order.create",
  "purchasing.order.update",
  "purchasing.order.submit",
  "purchasing.order.export",
  "purchasing.order.send",
  "purchasing.order.cancel",
  "purchasing.order.close",
  "purchasing.receipt.read",
  "purchasing.receipt.create",
  "purchasing.return.read",
  "purchasing.return.create",
  "purchasing.suggestion.read",
  "purchasing.suggestion.generate",
  "purchasing.report.read",
  "purchasing.report.export",
];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  administrator: [
    "platform.organization.read",
    "platform.organization.update",
    "platform.team.read",
    "platform.team.invite",
    "platform.invitation.resend",
    "platform.invitation.cancel",
    "platform.team.assign_roles",
    "platform.team.disable",
    "platform.audit.read",
    "platform.module.read",
    "platform.capacity.read",
    "platform.plan.read",
    "inventory.product.read",
    "inventory.product.create",
    "inventory.product.update",
    "inventory.product.archive",
    "inventory.product.reactivate",
    "inventory.unit.read",
    "inventory.presentation.read",
    "inventory.presentation.create",
    "inventory.presentation.update",
    "inventory.location.read",
    "inventory.location.create",
    "inventory.location.update",
    "inventory.location.archive",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.minimum.read",
    "inventory.minimum.update",
    "inventory.dashboard.read",
    "inventory.entry.create",
    "inventory.opening.create",
    "inventory.exit.create",
    "inventory.transfer.create",
    "inventory.adjustment.create",
    "inventory.movement.reverse",
    "inventory.count.read",
    "inventory.count.create",
    "inventory.count.update",
    "inventory.count.apply",
    "inventory.import.create",
    "inventory.import.read",
    "inventory.import.confirm",
    "inventory.import.cancel",
    "inventory.export.create",
    "purchasing.supplier.read",
    "purchasing.supplier.create",
    "purchasing.supplier.update",
    "purchasing.product_supplier.read",
    "purchasing.product_supplier.create",
    "purchasing.product_supplier.update",
    "purchasing.cost.read",
    "purchasing.cost.record",
    "purchasing.order.read",
    "purchasing.order.create",
    "purchasing.order.update",
    "purchasing.order.submit",
    "purchasing.order.export",
    "purchasing.order.send",
    "purchasing.order.cancel",
    "purchasing.order.close",
    "purchasing.receipt.read",
    "purchasing.receipt.create",
    "purchasing.return.read",
    "purchasing.return.create",
    "purchasing.suggestion.read",
    "purchasing.suggestion.generate",
    "purchasing.report.read",
    "purchasing.report.export",
  ],
  warehouse: [
    "platform.organization.read",
    "platform.module.read",
    "platform.capacity.read",
    "inventory.product.read",
    "inventory.product.create",
    "inventory.product.update",
    "inventory.product.archive",
    "inventory.product.reactivate",
    "inventory.unit.read",
    "inventory.presentation.read",
    "inventory.presentation.create",
    "inventory.presentation.update",
    "inventory.location.read",
    "inventory.location.create",
    "inventory.location.update",
    "inventory.location.archive",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.minimum.read",
    "inventory.minimum.update",
    "inventory.dashboard.read",
    "inventory.entry.create",
    "inventory.opening.create",
    "inventory.exit.create",
    "inventory.transfer.create",
    "inventory.adjustment.create",
    "inventory.movement.reverse",
    "inventory.count.read",
    "inventory.count.create",
    "inventory.count.update",
    "inventory.count.apply",
    "inventory.import.create",
    "inventory.import.read",
    "inventory.import.confirm",
    "inventory.import.cancel",
    "inventory.export.create",
  ],
  buyer: [
    "platform.organization.read",
    "platform.module.read",
    "platform.capacity.read",
    "inventory.product.read",
    "inventory.unit.read",
    "inventory.presentation.read",
    "inventory.location.read",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.minimum.read",
    "inventory.dashboard.read",
    "inventory.export.create",
    "purchasing.supplier.read",
    "purchasing.supplier.create",
    "purchasing.supplier.update",
    "purchasing.product_supplier.read",
    "purchasing.product_supplier.create",
    "purchasing.product_supplier.update",
    "purchasing.cost.read",
    "purchasing.cost.record",
    "purchasing.order.read",
    "purchasing.order.create",
    "purchasing.order.update",
    "purchasing.order.submit",
    "purchasing.order.export",
    "purchasing.order.send",
    "purchasing.order.cancel",
    "purchasing.order.close",
    "purchasing.receipt.read",
    "purchasing.receipt.create",
    "purchasing.return.read",
    "purchasing.return.create",
    "purchasing.suggestion.read",
    "purchasing.suggestion.generate",
    "purchasing.report.read",
    "purchasing.report.export",
  ],
  viewer: [
    "platform.organization.read",
    "platform.module.read",
    "platform.capacity.read",
    "inventory.product.read",
    "inventory.unit.read",
    "inventory.presentation.read",
    "inventory.location.read",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.minimum.read",
    "inventory.dashboard.read",
    "inventory.count.read",
    "inventory.export.create",
    "purchasing.supplier.read",
    "purchasing.product_supplier.read",
    "purchasing.order.read",
    "purchasing.receipt.read",
    "purchasing.return.read",
    "purchasing.suggestion.read",
    "purchasing.report.read",
    "purchasing.report.export",
  ],
};

export function isRole(value: unknown): value is Role {
  return (
    typeof value === "string" && (ROLES as readonly string[]).includes(value)
  );
}

export function isPermission(value: unknown): value is Permission {
  return (
    typeof value === "string" &&
    (PERMISSIONS as readonly string[]).includes(value)
  );
}
